### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by Fraasi** [CodingTrain/project-trainsite-frontend#13]
Not to forget to finish the header.  
Header needs to be changed to styled components and there is currently no 'small screen' navigation.  
One can see how it is currently on the website and just port it, shouldn' be too difficult.  
But keep in mind that the old site had some problems with this, CodingTrain/website#904, so we should at least try to avoid making the same mistakes.

**Comment by Fraasi** [comment]
I made a nav [button](https://codepen.io/Fraasi/pen/oJVjqw).

**Comment by Fraasi** [comment]
Ok, this is almost done, but I ran into a few problems, that needs a review/opinion/...
* [ ] Couldn't think of a way to reuse the header nav to this, as they are styled totally differently, so I made a it's own component, not sure if this is the best approach.
* [x] ~~couldn't get the sweet background-blur to work, so in this one overlay just darkens the background~~
* [x] ~~can't get the backdrop to be 'non-clickable-throught' 😄 ie. 'pointer-events: none;' is not working, no matter the z-index or place in the DOM.~~
* [x] ~~It was easier to write plain css, so still needs to be translated to styled-components.~~

Component [here](https://github.com/Fraasi/project-trainsite-frontend/tree/mobile-nav/src/components/MobileNavigation).

edit: I just needed some sleep...

**Comment by meiamsome** [comment]
Todo on this:
 - remove the use of the ref by refactoring a bit

**Comment by Fraasi** [comment]
resolved in #17
