### ISSUE TITLE
Update react (& other dependencies)

### ISSUE THREAD

**Issue by Fraasi** [CodingTrain/project-trainsite-frontend#31]
Now that react hooks are a big thing, sooner or later someone is trying to use them, but our version of react is 16.7.0 at the moment and hooks came in version 16.8.0.  

Maybe `npm update` is sufficient here to update all the dependencies as well without (hopefully) breaking anything, or should we be more carefull and just update react?

**Comment by gruselhaus** [comment]
Fixed in #34
