### ISSUE TITLE
Create the Button element

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/project-trainsite-frontend#4]
The Button element is used in various places across the website, and needs to support the current hover animation, and multiple colours. Please keep in mind the potential that this will likely need to wrap a `react-router` `<Link />` element unless the link is external.

An example, from the [home page](https://thecodingtrain.com/):
![screenshot from 2019-01-06 02-16-54](https://user-images.githubusercontent.com/1187491/50731308-43470480-1159-11e9-815f-84d11c7cb4ac.png)

**Comment by Fraasi** [comment]
I fiddled a little around the button idea and got this far:  
you call it like this
```js
        <Button
          link='https://thecodingtrain.com/'
          color='purple'
          size='thin'
          text='button text'
        />
        <Button
          link='https://thecodingtrain.com/'
          color='red'
          size='fat'
          text='button no2 text'
        />
```
and this is the code  
```js
import React, { Component } from 'react';
import './index.css';

interface ButtonProps {
  link?: string,
  color?: string,
  size?: string,
  text: string,
}

const colours: { [index:string] : string } = {
  blue: '#2494C1',
  green: '#49BB6C',
  purple: '#9659A7',
  red: '#F35956',
}

export default class Button extends Component<ButtonProps> {
  render() {
    const { link, color = '#9659A7', size = '18px', text } = this.props
    const height = size === 'fat' ? '20px' : '18px'
    return (
      <div 
        className='Button'
        style={{
          backgroundColor: colours[color],
          height: height
        }}>
       <a href={link}>{text}</a>
      </div>
    );
  }
}
```
and this is what it looks like
![2019-01-08_2115](https://user-images.githubusercontent.com/22402899/50853734-c3ed4700-138b-11e9-8061-82da4577899c.png)
We can do a check on the link and if it isn't external link then return react router element of some sort.  
Any thoughts about this?

**Comment by meiamsome** [comment]
Looks good @Fraasi, although it looks like the `a` tag has its own shadow in your screenshot.

```typescript
const colours: { [index:string] : string } = {
  blue: '#2494C1',
  green: '#49BB6C',
  purple: '#9659A7',
  red: '#F35956',
}
```

This seems like we're mixing the realm of CSS and JS more than we were supposed to by hard coding them in the same file. I can see two answers here -
1) Create a helper file for this and other styles in the JS so that they are centralized there at least
or
2) Perhaps something like
```typescript
const colours: { [index:string] : string } = {
  blue: 'var(--ct-blue, #2494C1)',
  green: 'var(--ct-green, #49BB6C)',
  purple: 'var(--ct-purple, #9659A7)',
  red: 'var(--ct-red, #F35956)',
}
```

You could also do both 1 & 2 by centralising the definition with `var` but honestly this isn't ideal either. I think doing css-in-js may actually just be a great idea for a lot of the behaviour we're missing from `var`...

**Comment by Fraasi** [comment]
> This seems like we're mixing the realm of CSS and JS more than we were supposed to

Yeah, but this was just a quick demo to get some feedback. I could put the color-prop in the className and then just write in css  
```css
.Button.purple {
    background-color: var(--ct-purple, #9659A7),
}
```
for all the colors.  

We really should make a decision on how to do styling soon.  

>I think doing css-in-js may actually just be a great idea for a lot of the behaviour we're missing from var...

I'm starting to lean towards [styled-components](https://www.styled-components.com/).
And how about that, they have a style a button example on the front page 😄 

>it looks like the a tag has its own shadow in your screenshot.

You were right, how did that get in there? 🤔

**Comment by Fraasi** [comment]
> You were right, how did that get in there? 🤔

Didn't solve this one, remains a mystery. 🤷

So I think I got the basics of this button thing written with styled-components. It should be easy to build upon this as later needed. I will wait until #11 is resolved to make a pull request. For the curious kind, you can [take a peek here.](https://github.com/Fraasi/project-trainsite-frontend/tree/test/button/src/components/Button)
