### ISSUE TITLE
Create the website's Footer element

### ISSUE THREAD

**Issue by meiamsome** [CodingTrain/project-trainsite-frontend#6]
The website footer currently has three equally sized segments, all linking externally. I'd suggest not overloading the Button element from #4 as they are significantly different. The URLs can be hard coded for now.

An example from the [home page](https://thecodingtrain.com/):
![screenshot from 2019-01-06 02-27-06](https://user-images.githubusercontent.com/1187491/50731373-c3ba3500-115a-11e9-92ee-97744eb70bcd.png)

**Comment by meiamsome** [comment]
@Fraasi did you have code for this (& the header) already, or shall we leave this as open for people to claim?

**Comment by Fraasi** [comment]
@meiamsome yes, [kind of](https://fraasi.github.io/trainsite-playground/) :bowtie:  
But thats a good start. I can take this and the header. I'll see where I get to later today.

Edit: Done. See #7  & #8.
